### PR TITLE
Feature/1 kundkontolista

### PR DESCRIPTION
**Pull request by EmranAhmed00**
code review

### CODE REVIEW

**Comment by tombergqvist2** [comment]
It works!

**Comment by tombergqvist2** [comment]
Oops, still works!

**Comment by tombergqvist2** [comment]
It works!

**Review by tombergqvist2 — APPROVED** [review]
This works!

**Comment by EmranAhmed00** [comment]
good logic

**Comment by EmranAhmed00** [comment]
okay

**Comment by EmranAhmed00** [comment]
well done

**Pull request merged**
